# Generated by Django 4.0.5 on 2022-07-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='data_de_criacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da Tarefa'),
        ),
    ]
