# Generated by Django 4.0.5 on 2022-07-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todomodel_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='tarefa',
            field=models.CharField(max_length=120, verbose_name='Tarefa'),
        ),
    ]
